runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/v1/timings/*
  script: main.app
  login: admin
- url: /api/v1/.*
  script: main.app
- url: /scripts/*
  static_dir: public/scripts
- url: /
  static_files: public/day.html
  upload: public/day.html

libraries:
- name: ssl
  version: latest
